name: 'Tmp'

on:
  push

jobs:
  tmp_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: nordcraftengine/documentation/.github/workflows/create_release.yml@full-docs
      secrets: inherit